"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.LONG_PRESS_DURATION = exports.ANIMATION_DURATION = exports.STORY_ANIMATION_DURATION = exports.STORY_AVATAR_SIZE = exports.AVATAR_OFFSET = exports.AVATAR_SIZE = exports.STROKE_WIDTH = exports.LOADER_URL = exports.LOADER_ID = exports.CLOSE_COLOR = exports.BACKGROUND_COLOR = exports.PROGRESS_ACTIVE_COLOR = exports.PROGRESS_COLOR = exports.SEEN_LOADER_COLORS = exports.LOADER_COLORS = exports.DEFAULT_COLORS = exports.STORAGE_KEY = exports.HEIGHT = exports.WIDTH = void 0;
const react_native_1 = require("react-native");
_a = react_native_1.Dimensions.get('screen'), exports.WIDTH = _a.width, exports.HEIGHT = _a.height;
exports.STORAGE_KEY = '@birdwingo/react-native-instagram-stories';
exports.DEFAULT_COLORS = ['#F7B801', '#F18701', '#F35B04', '#F5301E', '#C81D4E', '#8F1D4E'];
exports.LOADER_COLORS = ['#FFF'];
exports.SEEN_LOADER_COLORS = ['#2A2A2C'];
exports.PROGRESS_COLOR = '#00000099';
exports.PROGRESS_ACTIVE_COLOR = '#FFFFFF';
exports.BACKGROUND_COLOR = '#000000';
exports.CLOSE_COLOR = '#00000099';
exports.LOADER_ID = 'gradient';
exports.LOADER_URL = `url(#${exports.LOADER_ID})`;
exports.STROKE_WIDTH = 2;
exports.AVATAR_SIZE = 60;
exports.AVATAR_OFFSET = 5;
exports.STORY_AVATAR_SIZE = 26;
exports.STORY_ANIMATION_DURATION = 800;
exports.ANIMATION_DURATION = 10000;
exports.LONG_PRESS_DURATION = 500;
//# sourceMappingURL=index.js.map